#!/bin/bash

CMD="mvn clean test" # Command that runs your tests

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then
      echo "failed $CMD"
      exit 1
fi

exit 0